/** Shared Arabic UI strings — inclusive for men & women (unmarked/Gulf neutral). */
export const ar = {
  brand: {
    nameAr: "أصول",
    nameEn: "OSOOL",
    descriptor: "للشعر والفروة",
    tagline: "العناية تبدأ من الأصل",
    campaign: "نبدأ من الأصل، مو من الأعراض",
  },
  nav: {
    home: "الرئيسية",
    collection: "المنتجات",
    protocol: "البروتوكول",
    science: "العلم",
    guarantee: "الضمان",
    contact: "تواصل معنا",
    about: "من نحن",
    cart: "السلة",
    menu: "القائمة",
  },
  announcement:
    "توصيل لكل السعودية · دفع عند الاستلام · ضمان تجربة ٣٠ يوم",
  trust: {
    cod: { label: "دفع عند الاستلام", sub: "ولا ريال قبل ما يوصلك" },
    delivery: { label: "توصيل لكل السعودية", sub: "٢–٤ أيام عمل" },
    discreet: { label: "تغليف مقفل", sub: "ما فيه أي تفاصيل من الخارج" },
    guarantee: {
      label: "ضمان ٣٠ يوم",
      sub: "جرّب براحتك — النتيجة، أو ترجع فلوسك",
    },
    whatsapp: { label: "دعم واتساب", sub: "نرد خلال ساعة" },
  },
  cta: {
    seeProducts: "شوف المنتجات",
    seeCause: "وش سبب تساقطك؟",
    addToCart: "أضف للسلة",
    added: "تم",
    startSystem: "شوف النظام الكامل",
    readStory: "اقرأ قصتنا",
    seeReviews: "شوف كل التقييمات",
    whatsapp: "كلّمنا واتساب",
    checkout: "أكمل الطلب",
    checkoutSubmit: "تأكيد الطلب — دفع عند الاستلام",
    continueShopping: "كمّل تسوّقك",
  },
  cart: {
    title: "سلّتك",
    empty: "سلّتك فاضية",
    emptySub: "ابدأ من هنا — اختار السبب اللي يشبه وضعك",
    crossSellTitle: "كمّل النظام",
    crossSellSubOne: "غطّيت سبب واحد. باقي سبب واحد.",
    crossSellSubTwo: "غطّيت سبب واحد. باقي سببين.",
    systemComplete:
      "النظام كامل ✓ — السيروم للبصيلة، التونك للمخزون، والمقشّر للفروة. هذي أفضل تركيبة.",
    total: "الإجمالي",
    freeShip: "التوصيل مجاني · شامل الضريبة",
    codNote: "الدفع كاش عند الاستلام",
    remove: "احذف",
    decrease: "قلّل",
    increase: "زِد",
  },
  checkout: {
    title: "خطوة واحدة وينتهي طلبك",
    sub: "ما نطلب منك بطاقة ولا حساب. بس اسمك ورقمك.",
    summary: "ملخص طلبك",
    shipping: "التوصيل",
    free: "مجاني",
    nameLabel: "الاسم",
    namePlaceholder: "اسمك الكامل",
    phoneLabel: "رقم الجوال",
    phonePlaceholder: "05X XXX XXXX",
    phoneHelp: "نتواصل معك على هذا الرقم لتأكيد الطلب",
    submitting: "قاعدين نثبت طلبك…",
    errorGeneric: "صار خطأ. جرّب مرة ثانية أو كلّمنا واتساب.",
    guarantee1: "تدفع كاش لما يوصلك — وتقدر ترفض الاستلام",
    guarantee2: "تغليف مقفل، ما فيه أي تفاصيل من الخارج",
    guarantee3: "ضمان تجربة ٣٠ يوم",
    consent: "بتأكيدك للطلب أنت توافق على",
    terms: "الشروط والأحكام",
    and: "و",
    privacy: "سياسة الخصوصية",
  },
  thankYou: {
    title: "تم — طلبك وصلنا",
    orderNo: "رقم طلبك",
    savedOn: "حفظنا طلبك على الرقم",
    nextTitle: "وش يصير الآن؟",
    step1Title: "نكلّمك للتأكيد",
    step1Body:
      "نتواصل معك خلال ٢٤ ساعة نأكد الطلب ونأخذ عنوانك بالتفصيل.",
    step2Title: "نشحنه",
    step2Body:
      "بعد التأكيد نجهّز طلبك ويوصلك خلال ٢–٤ أيام عمل. التغليف مقفل.",
    step3Title: "تدفع عند الاستلام",
    step3Body: "كاش للمندوب. ولا ريال قبل.",
    saveNumberTitle: "مهم — احفظ رقمنا",
    saveNumberBody:
      "كثير من الطلبات ما تُشحن لأن المكالمة ما ينرد عليها. احفظ رقمنا، وإذا شفت مكالمة منه رد عليها.",
    whatsappConfirm: "كلّمني على واتساب بدل المكالمة",
    backHome: "ارجع للمتجر",
  },
  common: {
    from: "من",
    reviews: "تقييم",
    verified: "تقييمات موثّقة",
    sar: "ريال",
    perDay: "يعني أقل من",
    perDaySuffix: "ريال باليوم",
    mostPopular: "الأكثر طلباً",
    bestValue: "أفضل قيمة",
    causeOf: "يشتغل على السبب",
    thisProduct: "هذا اللي يشتغل عليه هذا المنتج",
    coverAll: "تبي تغطي الأسباب الثلاثة؟",
    imageSoon: "الصورة قريباً",
    close: "إغلاق",
  },
  footer: {
    blurb:
      "أصول — منظومة عناية بالفروة والجذور. ثلاث أسباب، ثلاث خطوات، بمكوّنات مسمّاة وتراكيز مكتوبة.",
    shop: "التسوق",
    help: "مساعدة",
    legal: "قانوني",
    policies: "السياسات",
    returns: "الاستبدال والإرجاع",
    privacy: "الخصوصية",
    terms: "الشروط والأحكام",
    shipping: "سياسة التوصيل",
    faq: "الأسئلة الشائعة",
    copyright: "© أصول. جميع الحقوق محفوظة.",
    vat: "الأسعار شاملة ضريبة القيمة المضافة.",
    crPlaceholder: "السجل التجاري يُضاف عند الإصدار",
  },
  whatsapp: {
    label: "واتساب",
    prefill: "مرحباً، عندي سؤال عن منتجات أصول",
  },
} as const;
